start_idx: 0 
end_idx: null
sample_n_frames: 81
aspect_ratio: 1.73
seed: 42
precision: 'bf16'
task: 'i2v'
base_dir: 'weights/Wan2.1-I2V-14B-480P'
resolution: [480]
num_frames: 81
batch_size: 1
fps: 16
json_path: temp_data/temp_input_data.json
save_dir: temp_data/480
extract_fps: 16
model_type: 'wanx'
vae_path: 'weights/Wan2.1-I2V-14B-480P/Wan2.1_VAE.pth'
image_processor_path: 'weights/Wan2.1-I2V-14B-480P/xlm-roberta-large'
image_encoder_path: 'weights/Wan2.1-I2V-14B-480P/models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth'
tokenizer_path: 'weights/Wan2.1-I2V-14B-480P/google/umt5-xxl'
text_encoder_path: 'weights/Wan2.1-I2V-14B-480P/models_t5_umt5-xxl-enc-bf16.pth'
max_sequence_length: 512